= srcdeps-mvn-git-revision-quickstart

A project containing a dependency on a source revision of another project

== System requirements

* Maven 3.3.1 or newer
* Java 7 or newer

== Recommended study order

* link:.mvn/extensions.xml[`.mvn/extensions.xml`]
* link:srcdeps.yaml[`srcdeps.yaml`] and its documentation under link:../../../doc/srcdeps-maven-configuration.adoc and
  https://github.com/srcdeps/srcdeps-core/blob/master/doc/srcdeps.yaml .
* The version string in link:pom.xml#L46[`pom.xml`]
* Issue `mvn clean install` on command line in the directory where this README file resides.
* Check in the output of the above `mvn` command if the
  link:jar/src/test/java/org/l2x6/srcdeps/quickstarts/mvn/git/revision/AppClientTest.java#L26[test] passed
* Check if the version `0.0.1-SRC-revision-66ea95d890531f4eaaa5aa04a9b1c69b409dcd0b` of
  `org.l2x6.maven.srcdeps.itest:srcdeps-test-artifact` was installed in your local Maven repository.
* Check the directory where the `srcdeps-test-artifact` was built:
  `${maven.repo.local}/../srcdeps/org.l2x6.maven.srcdeps.itest` - i.e. typically
  `~/.m2/srcdeps/org.l2x6.maven.srcdeps.itest`

== Feedback

via link:https://github.com/srcdeps/srcdeps-maven/issues[scrdeps-maven Github Issues]