= Srcdeps Maven

ifdef::env-github[]
[link=https://travis-ci.org/srcdeps/srcdeps-maven]
image:https://travis-ci.org/srcdeps/srcdeps-maven.svg?branch=master["Build Status", link="https://travis-ci.org/srcdeps/srcdeps-maven"]
endif::[]

A Maven Core Extension for building dependencies from their sources during the build.

= What is this good for?

Srcdeps alleviates some of the pains that arise from implementing Continuous Delivery in Maven projects. With srcdeps,
a module can depend on a specific revision of another module. For instance, a module `web-banking-frontend` could
depend on `account-balance-microservice` at git revision `abc123`, without requiring the
`account-balance-microservice` to perform a complete Maven release.


== Srcdeps support for Maven

Currently, the srcdeps toolkit supports only Maven 3.3.1+, although the
link:https://github.com/srcdeps/srcdeps-core[Srcdeps Core]
library has an ambition to be generic enough so that a support for other Java build tools such as Gradle or sbt can be
added (contributions are welcome!).

The present solution for Maven is leveraging the concept of Maven Core Extensions introduced in Maven 3.3.1.
In particular, we provide an implementation of `LocalRepositoryManager` that delegates all the usual artifact
lookup work to the standard local repository manager available in Maven class path, but it is watching carefully,
if the requested artifact contains `-SRC-` in its version string. For such ones, the `srcdeps-core` library is
called, to build what is necessary and install it to the Maven local repository. In other words, the dependencies
are built and installed while they are looked up.

=== How to configure for Maven:

==== 1. `.mvn/extensions.xml`

`srcdeps-maven-local-repository` needs to be declared as a Maven Core Extension in `.mvn/extensions.xml` of the maven project.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<extensions>
  <extension>
    <groupId>org.l2x6.maven.srcdeps</groupId>
    <artifactId>srcdeps-maven-local-repository</artifactId>
    <version>3.0.0</version><!-- @srcdeps.version@ -->
  </extension>
  <extension>
    <groupId>org.srcdeps.mvn</groupId>
    <artifactId>srcdeps-maven-enforcer</artifactId><!-- to prevent srcdeps in releases -->
    <version>3.0.0</version><!-- @srcdeps.version@ -->
  </extension>
</extensions>
----

==== 2. `.mvn/srcdeps.yaml`

A few settings have to be configured in `.mvn/srcdeps.yaml` file. Especially, the mapping from groupId's of
dependencies to SCM repositiries where their sources reside. This is a minimal `.mvn/srcdeps.yaml` file. Please
refer to link:https://github.com/srcdeps/srcdeps-core/tree/master/doc/srcdeps.yaml[srcdeps.yaml reference] for full
reference.

[source,yaml]
----
configModelVersion: 1.1
repositories:
  org.my-group:
    selectors:
    - org.my-group:*:*  # if one of the selectors matches the groupId of a -SRC- dependency,
                        # then the following urls will be used to build that dependency
    urls:
    - https://github.com/my-org/my-project.git  # If you list multiple SCM repos here then only
                                                # the first successful checkout will count

----


=== Override `.mvn/srcdeps.yaml` options on the command line

All options configurable in `.mvn/srcdeps.yaml` can be overriden through system properties passed on the command
line. To construct the property name, just take the `srcdeps.` prefix and append the `.mvn/srcdeps.yaml` DOM
path to the option you want to override.

For example, to dynamically change the verbosity you would have to issue something like

[source,shell]
----
mvn ... -Dsrcdeps.verbosity=debug
----

To *replace* `https://github.com/my-org/my-project.git` with your local git repository in the above
example, you need to invoke something like

[source,shell]
----
mvn ... -Dsrcdeps.repositories[org.my-group].urls[0]=/home/my-user/repos/my-project/.git
----

To *append* your local git repository to the list of URLs in the above example, you need to invoke something like

[source,shell]
----
mvn ... -Dsrcdeps.repositories[org.my-group].urls[1]=/home/my-user/repos/my-project/.git
----

To *prepend* your local git repository to the list of URLs in the above example, you need to invoke something like

[source,shell]
----
mvn ... -Dsrcdeps.repositories[org.my-group].urls[-1]=/home/my-user/repos/my-project/.git
----

To *replace the whole list* with a new list of URLs in the above example, you need to invoke something like

[source,shell]
----
mvn ... -Dsrcdeps.repositories[org.my-group].urls=/home/my-user/repos/my-project/.git,https://github.com/my-user/my-project.git
----


=== Examples a.k.a. Quickstarts

There is a couple of ready-to-build self-contained examples in the
link:srcdeps-maven-quickstarts[srcdeps-maven-quickstarts] directory. Perhaps the most prominent of them is the
link:srcdeps-maven-quickstarts/srcdeps-mvn-git-revision-quickstart[srcdeps-mvn-git-revision-quickstart] that
demonstrates how a project can depend on a source revision of another project.

== How Srcdeps tools work

* Srcdeps tools are supposed to build dependencies with versions matching `{whatever}-SRC-{srcVersionType}-{srcVersion}`
* Any artifact having such a `-SRC-` version that is requested during the build needs to have an associated SCM
  repository in the configuration. For Maven, the configuration is stored in `.mvn/srcdeps.yaml` under the top level
  directory of the project.
* The URL of the associated SCM repository is used to fetch the sources of the dependency and checkout the desired revision.
  For Maven the sources are cloned to `${maven.repo.local}/../srcdeps/${scmRepo.id}`
* Then, `srcdeps-core` changes the version in the sources to `{whatever}-SRC-{srcVersionType}-{srcVersion}`
  using Versions Maven Plugin
* And finally, `srcdeps-core` builds the artifacts and installs them to the local Maven repository
* For Maven, the `-SRC-` dependencies are build only if they are not found in local repository - so they prolong the
  build only when upgrading.


== Misc.

* All code and contributions are under link:/LICENSE.txt[Apache License]
* Issues and Discussions: https://github.com/srcdeps/srcdeps-maven-plugin/issues
* Slides link:http://ppalaga.github.io/presentations/160909-ci-cd-with-maven-and-srcdeps/160906-srcdeps.html[Continuous Integration/Delivery with Maven and srcdeps] 2016-09-09


=== Legacy note

Originally, the present project provided a Maven plugin called `srcdeps-maven-plugin` that worked fairly well in most situations, but it turned out soon that the Maven Plugin API is not rich enough to allow for catching dependencies of
all possible kinds. Most notably, the given project's parent pom and imports in `dependencyManagement` sections were
resolved by Maven even before the plugin was initialized. Thus, if the given project's parent pom had a `-SRC-`
version, the build failed with a missing artifact error message, simply because it happened before
`srcdeps-maven-plugin` could do anything.

An outdated presentation about the abandoned `srcdeps-maven-plugin`: http://ppalaga.github.io/presentations/150929-srcdeps-maven-plugin/150929-srcdeps-maven-plugin.html


